apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: task-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # ← IMPORTANT
  resources:
    requests:
      storage: 1Gi